// A HorizontalLayout is used to arrange children side-by-side.

import { Button } from "std-widgets.slint";
export component addWindow inherits Window {
    title: "Mira Downloader";
    default-font-family: @tr("roboto");
    default-font-size: 12px;
    min-height: 500px;
    min-width: 900px;

HorizontalLayout {
    // --- Column 1 (30% Width) ---
    left-pane := Rectangle {
        // Setting the width to 30% of the parent layout's available space.
        width: 25%;
        background: #1f2937; // Blue background


        HorizontalLayout {
        width: 100%;
        height: 100%;
        VerticalLayout {
            padding: 15px;
            horizontal-stretch: 1;
            // Text label for this column

            app-brand := Rectangle {
                height: 10%;
                width: 100%;
            Text {
                text: "Mira Downloader";
                color: #a684ff;
                font-size: 18px;
                font-weight: 600;
                horizontal-alignment: center;
            }}

            // Add a flexible space to center the text vertically
            spacer := Rectangle {
            height: 1px;
            border-color: #364153;
            border-width: 1px;
            }

            download-states :=VerticalLayout {
                height: 20%;
                padding-top: 20px;
                spacing: 10px;
                padding-bottom: 20px;

                Button {
                    width: 100%;
                    text: "Active";
                }

                 Button {
                    width: 100%;
                    text: "Completed";
                }
            }

            spacer2 := Rectangle {
            height: 1px;
            border-color: #364153;
            border-width: 1px;
            }


        }

        divider := Rectangle {
            width: 2px;
            height: 100%;
            border-color: #364153;
            border-width: 2px;
        }
    }}

    // --- Column 2 (70% Width) ---
    main-pane := Rectangle {
        // Setting the width to 70% of the parent layout's available space.
        width: 75%;
        background: #1f2937; // Green background

        VerticalLayout {
            padding: 15px;
            // Text label for this column
            Text {
                text: "Column 2 (70%)";
                color: white;
                font-size: 18px;
                horizontal-alignment: center;
            }
            // Add a flexible space to center the text vertically
            Rectangle { vertical-stretch: 1; }
            Text {
                text: "Main Content / Detail View Area";
                color: #ecf0f1;
                horizontal-alignment: center;
            }
            Rectangle { vertical-stretch: 1; }
        }
    }
}

}

